### ISSUE TITLE
CatalogServiceImpl 

### ISSUE THREAD

**Issue by wizzlerr** [G-Maan/music-recommendation#7]
Rename to CatalogService

Use @RequiredArgsConstructor from lombok to inject spring dependencies

private CatalogRepository catalogRepository; <- make it final

```
@Override
    public CatalogDTO getCatalog(int id) {
        Optional<Catalog> catalog = this.catalogRepository.findById(id);
        return catalog.isPresent() ? new CatalogDTO(catalog.get()) : null;
    }
```

Dont return nulls. Returning nulls leads to NPE. Either return Optional<CatalogDTO> or throw exception.

**Comment by G-Maan** [comment]
Deleted service and repository from this project.
Added @RequiredArgsConstructor to all projects and made instances final
